### ISSUE TITLE
Cannot run hammett self test in either Python 3.6 or 3.7.

### ISSUE THREAD

**Issue by rec** [boxed/hammett#2]
I fixed a bunch of minor flake8 quibbles in a new branch, but I can't get the tests to pass, not even from HEAD!

I created clean virtualenvs just for this purpose.  I'm on MacOS:  `Darwin bantam.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64`.

Let me know how I can help with this!  :-)

------

     $ new-env hammett-3.7 python3.7  # my script to create an empty virtualenv
     $ pip install -r requirements.txt
     $ python -m hammett

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/code_external/hammett/hammett/__main__.py", line 3, in <module>
        exit(main_cli())
      File "/code_external/hammett/hammett/__init__.py", line 556, in main_cli
        disable_assert_analyze=args.disable_assert_analyze,
      File "/code_external/hammett/hammett/__init__.py", line 470, in main
        execute_test_function(module_name + '.' + name, f, module_request)
      File "/code_external/hammett/hammett/impl.py", line 527, in execute_test_function
        return run_test(_name, _f, module_request)
      File "/code_external/hammett/hammett/impl.py", line 400, in run_test
        inc_test_result(SKIPPED, _name, _f, stdout='', stderr='')
    TypeError: inc_test_result() missing 1 required positional argument: 'duration'

-------

     $ new-env hammett-3.6 python3.6  # my script to create an empty virtualenv
     $ pip install -r requirements.txt
     $ python -m hammett

    Failed to load module tests.suites.suite_2_module_marker_skip.tests.test_foo:
    Traceback (most recent call last):
      File "/code_external/hammett/hammett/__init__.py", line 428, in main
        spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "tests/suites/suite_2_module_marker_skip/tests/test_foo.py", line 3, in <module>
        pytestmark = pytest.mark.skip
    AttributeError: module 'hammett.mark' has no attribute 'skip'

**Comment by boxed** [comment]
Hmm.. yea the first thing there is me being silly and not running the test suite myself before committing. Early days is cowboy times!

I've pushed a fix to master that fixes this. I can now run the tests again.

The second crash seems to be that you're trying to use hammett to run the test suite for hammett. I don't intend to support that. The hammett test suite uses unittest (ugh) to not end up in a weird bootstrap situation. Just do "make test" in the repo and you should be good to go.

**Comment by rec** [comment]
DOH, makes sense it can't test itself.

I pulled your changes and they do work on Python 3.7!  Not so on 3.6.

I'll send out a quickie pull request for the 10% of the flake8 issues that were actually useful, and then spent 10 mins looking into 3.6.

**Comment by boxed** [comment]
Cool! I think I might have fixed the 3.6 problem you saw with sorting local variables before printing. I'm closing this ticket now.
